version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - '3000:3000'
    depends_on:
      - admin-service
      - product-service
      - category-service
      - checkout-service
    networks:
      - app-network

  admin-service:
    build: ./admin-service
    container_name: admin-service
    ports:
      - '4002:4002'
    networks:
      - app-network
    environment:
      MONGO_DB_URL: mongodb+srv://ibraheemshahid:ibraheem@clusterib.2sdfvqt.mongodb.net/admin-db?retryWrites=true&w=majority&appName=Clusterib
      JWT_SECRET: supersecret123

  product-service:
    build: ./products-service
    container_name: product-service
    ports:
      - '4000:4000'
    networks:
      - app-network
    environment:
      MONGO_DB_URL: mongodb+srv://ibraheemshahid:ibraheem@clusterib.2sdfvqt.mongodb.net/product?retryWrites=true&w=majority&appName=Clusterib

  category-service:
    build: ./category-service
    container_name: category-service
    ports:
      - '4001:4001'
    networks:
      - app-network
    environment:
      MONGO_URL: mongodb+srv://ibraheemshahid:ibraheem@clusterib.2sdfvqt.mongodb.net/category?retryWrites=true&w=majority&appName=Clusterib

  checkout-service:
    build: ./checkout-service
    container_name: checkout-service
    ports:
      - '4004:4004'
    networks:
      - app-network
    environment:
      MONGO_DB_URL: mongodb+srv://ibraheemshahid:ibraheem@clusterib.2sdfvqt.mongodb.net/order?retryWrites=true&w=majority&appName=Clusterib
      STRIPE_SECRET_KEY: sk_test_51RjaCc2YCFbZkcFKSEGzdRnXV3Kua2XxOGkooItFMa8hoNjdbTS0JOdWI687BlstQcLuZ9WO6ULGLXU6f4snBtAJ00ZvGFFmag

networks:
  app-network:
    driver: bridge
